// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.
//
// Site chrome rendered on every marketing page: nav, footer, brand, skip link, locale switcher. Includes the appearance-panel trigger label, the only appearance string a page needs before the panel opens.
//
// 39 messages. Import this barrel, never
// $lib/paraglide/messages.js — see docs/quran-system.md (Part 2, Message chunking).

export { brand_home_label } from "$lib/paraglide/messages/brand_home_label.js";
export { footer_about } from "$lib/paraglide/messages/footer_about.js";
export { footer_blurb } from "$lib/paraglide/messages/footer_blurb.js";
export { footer_bookmarks } from "$lib/paraglide/messages/footer_bookmarks.js";
export { footer_built_by } from "$lib/paraglide/messages/footer_built_by.js";
export { footer_company_heading } from "$lib/paraglide/messages/footer_company_heading.js";
export { footer_company_label } from "$lib/paraglide/messages/footer_company_label.js";
export { footer_contact } from "$lib/paraglide/messages/footer_contact.js";
export { footer_faq } from "$lib/paraglide/messages/footer_faq.js";
export { footer_legal_heading } from "$lib/paraglide/messages/footer_legal_heading.js";
export { footer_legal_label } from "$lib/paraglide/messages/footer_legal_label.js";
export { footer_privacy } from "$lib/paraglide/messages/footer_privacy.js";
export { footer_product_heading } from "$lib/paraglide/messages/footer_product_heading.js";
export { footer_product_label } from "$lib/paraglide/messages/footer_product_label.js";
export { footer_project_by } from "$lib/paraglide/messages/footer_project_by.js";
export { footer_read_quran } from "$lib/paraglide/messages/footer_read_quran.js";
export { footer_social_x } from "$lib/paraglide/messages/footer_social_x.js";
export { footer_terms } from "$lib/paraglide/messages/footer_terms.js";
export { footer_whats_inside } from "$lib/paraglide/messages/footer_whats_inside.js";
export { locale_ar_endonym } from "$lib/paraglide/messages/locale_ar_endonym.js";
export { locale_en_endonym } from "$lib/paraglide/messages/locale_en_endonym.js";
export { nav_account } from "$lib/paraglide/messages/nav_account.js";
export { nav_appearance } from "$lib/paraglide/messages/nav_appearance.js";
export { nav_change_language } from "$lib/paraglide/messages/nav_change_language.js";
export { nav_close_panel } from "$lib/paraglide/messages/nav_close_panel.js";
export { nav_language } from "$lib/paraglide/messages/nav_language.js";
export { nav_offline_detail } from "$lib/paraglide/messages/nav_offline_detail.js";
export { nav_offline_label } from "$lib/paraglide/messages/nav_offline_label.js";
export { nav_offline_title } from "$lib/paraglide/messages/nav_offline_title.js";
export { nav_open_panel } from "$lib/paraglide/messages/nav_open_panel.js";
export { nav_primary_label } from "$lib/paraglide/messages/nav_primary_label.js";
export { nav_search_quran } from "$lib/paraglide/messages/nav_search_quran.js";
export { nav_settings } from "$lib/paraglide/messages/nav_settings.js";
export { nav_sign_in } from "$lib/paraglide/messages/nav_sign_in.js";
export { nav_site_panel } from "$lib/paraglide/messages/nav_site_panel.js";
export { nav_theme } from "$lib/paraglide/messages/nav_theme.js";
export { nav_toggle_theme } from "$lib/paraglide/messages/nav_toggle_theme.js";
export { skip_to_content } from "$lib/paraglide/messages/skip_to_content.js";
export { tweaks_customize_appearance } from "$lib/paraglide/messages/tweaks_customize_appearance.js";
