// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.
//
// Reader appearance panel. Lazy: only downloaded once the panel is opened.
//
// 43 messages. Import this barrel, never
// $lib/paraglide/messages.js — see docs/quran-system.md (Part 2, Message chunking).

export { reader_accent } from "$lib/paraglide/messages/reader_accent.js";
export { reader_accent_azure } from "$lib/paraglide/messages/reader_accent_azure.js";
export { reader_accent_colour } from "$lib/paraglide/messages/reader_accent_colour.js";
export { reader_accent_gold } from "$lib/paraglide/messages/reader_accent_gold.js";
export { reader_accent_plum } from "$lib/paraglide/messages/reader_accent_plum.js";
export { reader_accent_reset } from "$lib/paraglide/messages/reader_accent_reset.js";
export { reader_accent_teal } from "$lib/paraglide/messages/reader_accent_teal.js";
export { reader_analytics } from "$lib/paraglide/messages/reader_analytics.js";
export { reader_background } from "$lib/paraglide/messages/reader_background.js";
export { reader_clear } from "$lib/paraglide/messages/reader_clear.js";
export { reader_close_appearance } from "$lib/paraglide/messages/reader_close_appearance.js";
export { reader_copy_css } from "$lib/paraglide/messages/reader_copy_css.js";
export { reader_custom_colours } from "$lib/paraglide/messages/reader_custom_colours.js";
export { reader_data_privacy } from "$lib/paraglide/messages/reader_data_privacy.js";
export { reader_mode } from "$lib/paraglide/messages/reader_mode.js";
export { reader_notifications } from "$lib/paraglide/messages/reader_notifications.js";
export { reader_notifications_blocked } from "$lib/paraglide/messages/reader_notifications_blocked.js";
export { reader_notifications_browser_unsupported } from "$lib/paraglide/messages/reader_notifications_browser_unsupported.js";
export { reader_notifications_checking } from "$lib/paraglide/messages/reader_notifications_checking.js";
export { reader_notifications_error } from "$lib/paraglide/messages/reader_notifications_error.js";
export { reader_notifications_off } from "$lib/paraglide/messages/reader_notifications_off.js";
export { reader_notifications_off_updates } from "$lib/paraglide/messages/reader_notifications_off_updates.js";
export { reader_notifications_on } from "$lib/paraglide/messages/reader_notifications_on.js";
export { reader_notifications_unavailable } from "$lib/paraglide/messages/reader_notifications_unavailable.js";
export { reader_off } from "$lib/paraglide/messages/reader_off.js";
export { reader_on } from "$lib/paraglide/messages/reader_on.js";
export { reader_performance } from "$lib/paraglide/messages/reader_performance.js";
export { reader_performance_reload } from "$lib/paraglide/messages/reader_performance_reload.js";
export { reader_pop } from "$lib/paraglide/messages/reader_pop.js";
export { reader_reset } from "$lib/paraglide/messages/reader_reset.js";
export { reader_settings } from "$lib/paraglide/messages/reader_settings.js";
export { reader_surface } from "$lib/paraglide/messages/reader_surface.js";
export { reader_surface_contrast } from "$lib/paraglide/messages/reader_surface_contrast.js";
export { reader_surface_contrast_note } from "$lib/paraglide/messages/reader_surface_contrast_note.js";
export { reader_surface_ink } from "$lib/paraglide/messages/reader_surface_ink.js";
export { reader_surface_ink_note } from "$lib/paraglide/messages/reader_surface_ink_note.js";
export { reader_surface_mocha } from "$lib/paraglide/messages/reader_surface_mocha.js";
export { reader_surface_mocha_note } from "$lib/paraglide/messages/reader_surface_mocha_note.js";
export { reader_surface_paper } from "$lib/paraglide/messages/reader_surface_paper.js";
export { reader_surface_paper_note } from "$lib/paraglide/messages/reader_surface_paper_note.js";
export { reader_surface_slate } from "$lib/paraglide/messages/reader_surface_slate.js";
export { reader_surface_slate_note } from "$lib/paraglide/messages/reader_surface_slate_note.js";
export { reader_theme_derived_note } from "$lib/paraglide/messages/reader_theme_derived_note.js";
