// AUTO-GENERATED by scripts/gen-message-namespaces.ts — do not edit.
//
// Dedicated /app/search page: query input, translation picker, merged results, download management. Lazy: downloaded whole when the search route loads.
//
// 34 messages. Import this barrel, never
// $lib/paraglide/messages.js — see docs/quran-system.md (Part 2, Message chunking).

export { search_arabic_only_note } from "$lib/paraglide/messages/search_arabic_only_note.js";
export { search_cached } from "$lib/paraglide/messages/search_cached.js";
export { search_count } from "$lib/paraglide/messages/search_count.js";
export { search_download } from "$lib/paraglide/messages/search_download.js";
export { search_downloading } from "$lib/paraglide/messages/search_downloading.js";
export { search_empty_idle } from "$lib/paraglide/messages/search_empty_idle.js";
export { search_error_section } from "$lib/paraglide/messages/search_error_section.js";
export { search_filter_none } from "$lib/paraglide/messages/search_filter_none.js";
export { search_filter_open } from "$lib/paraglide/messages/search_filter_open.js";
export { search_filter_placeholder } from "$lib/paraglide/messages/search_filter_placeholder.js";
export { search_filter_selected } from "$lib/paraglide/messages/search_filter_selected.js";
export { search_filter_title } from "$lib/paraglide/messages/search_filter_title.js";
export { search_input_label } from "$lib/paraglide/messages/search_input_label.js";
export { search_load_more } from "$lib/paraglide/messages/search_load_more.js";
export { search_loading_more } from "$lib/paraglide/messages/search_loading_more.js";
export { search_manage_storage } from "$lib/paraglide/messages/search_manage_storage.js";
export { search_nav_juz } from "$lib/paraglide/messages/search_nav_juz.js";
export { search_nav_page } from "$lib/paraglide/messages/search_nav_page.js";
export { search_nav_place_count } from "$lib/paraglide/messages/search_nav_place_count.js";
export { search_nav_place_meccan } from "$lib/paraglide/messages/search_nav_place_meccan.js";
export { search_nav_place_medinan } from "$lib/paraglide/messages/search_nav_place_medinan.js";
export { search_nav_sajda_obligatory } from "$lib/paraglide/messages/search_nav_sajda_obligatory.js";
export { search_nav_sajda_recommended } from "$lib/paraglide/messages/search_nav_sajda_recommended.js";
export { search_no_results } from "$lib/paraglide/messages/search_no_results.js";
export { search_pick_prompt } from "$lib/paraglide/messages/search_pick_prompt.js";
export { search_placeholder } from "$lib/paraglide/messages/search_placeholder.js";
export { search_results_label } from "$lib/paraglide/messages/search_results_label.js";
export { search_retry } from "$lib/paraglide/messages/search_retry.js";
export { search_rtl_disabled } from "$lib/paraglide/messages/search_rtl_disabled.js";
export { search_section_nav } from "$lib/paraglide/messages/search_section_nav.js";
export { search_section_quran } from "$lib/paraglide/messages/search_section_quran.js";
export { search_section_surahs } from "$lib/paraglide/messages/search_section_surahs.js";
export { search_title } from "$lib/paraglide/messages/search_title.js";
export { search_too_short } from "$lib/paraglide/messages/search_too_short.js";
